### ISSUE TITLE
Getting TypeError when attempting to serve a Notion Page

### ISSUE THREAD

**Issue by archiewood** [emoriarty/jekyll-notion#47]
Not sure if this is an error in the package, could be just me. I dont use ruby, so couldn't debug mutch, though did look in the Gem, and the line it's complaining about seems to be:

notion_page.rb:14
```
      config["data"]
```
May or may not be important but I'm using Windows, which is not officially supported by jekyll. Never had problems before with it though.

Also the " Database or page id is not provided. Cannot read from Notion." error confounded me a bit. Not sure if it's related, but i've definitely provided the id in the _config.yml

**Steps to reproduce:**
1. Following the steps in the README.
2. Contents of _config.yml:
```# Build settings
theme: minima
plugins:
  - jekyll-notion

notion:
  page:
    - id: b3bb13a3da194b61b0a62933fa77fc0f
 ```
3. contents of Gemfile
```
source "https://rubygems.org"
gem "jekyll", "~> 4.2.2"
gem "minima", "~> 2.5"
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

gem 'notion_to_md'
gem "webrick", "~> 1.7"
gem "jekyll-notion", "~> 2.0"
```
4. jekyll serve

**Expected outcome**
Serves my notion file to localhost:4000

**Result:**
> Configuration file: C:/[xxx]/_config.yml
>             Source: C:/[xxx]
>        Destination: C:/[xxx]/_site
>  Incremental build: disabled. Enable with --incremental
>       Generating...
>      Jekyll Notion: Database or page id is not provided. Cannot read from Notion.
>                     ------------------------------------------------
>       Jekyll 4.2.2   Please append `--trace` to the `serve` command
>                      for any additional information or backtrace.
>                     ------------------------------------------------
> C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-notion-2.0.0/lib/jekyll-notion/notion_page.rb:14:in `data_name': no implicit conversion of String into Integer (TypeError)
>         from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-notion-2.0.0/lib/jekyll-notion/factories/page_factory.rb:6:in `for'
>         from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-notion-2.0.0/lib/jekyll-notion/generator.rb:58:in `block in read_notion_pages'
>         from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-notion-2.0.0/lib/jekyll-notion/generator.rb:56:in `each'
>         from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-notion-2.0.0/lib/jekyll-notion/generator.rb:56:in `read_notion_pages'
>         from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-notion-2.0.0/lib/jekyll-notion/generator.rb:14:in `generate'
>         from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:193:in `block in generate'
>         from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:191:in `each'
>         from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:191:in `generate'
>         from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:79:in `process'
>         from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:28:in `process_site'
>         from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:65:in `build'
>         from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:36:in `process'
>         from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
>         from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `each'
>         from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
>         from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.2.2/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
>         from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
>         from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
>         from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
>         from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
>         from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
>         from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.2.2/exe/jekyll:15:in `<top (required)>'
>         from C:/Ruby31-x64/bin/jekyll:25:in `load'
>         from C:/Ruby31-x64/bin/jekyll:25:in `<main>'

**Comment by archiewood** [comment]
Hmmm okay, I think I have found a way around this.

in the README it suggests a valid _config.yml format is _notion: page: id:_ but for me it works if I change it to _notion: **pages:** id:_

![image](https://user-images.githubusercontent.com/58074498/161481549-84e586e2-c0ee-4f88-9122-a06a237b5489.png)

**Comment by emoriarty** [comment]
Hello @archiewood,

Thank you for your feedback.

Perhaps it's not clear in the README but there are two config types for pages (also for databases). When using `page`, it only accepts a `Hash` object with an `id` property. It cannot accept an array of ids. To provide a list of pages, we must specify the `pages` property and each id item has to be prefixed with a hyphen.

So, what you've mentioned as a workaround should not be working as follows

```
notion:
  page:
    - id: xxxxxxxxxxxxxxxxxx
```
Neither 
```
notion:
  pages:
    id: xxxxxxxxxxxxxxxxxx
```
Both examples would end up with the same error you've found.
```
notion_page.rb:14:in `data_name': no implicit conversion of String into Integer (TypeError)
```
Use only one `id` when declaring just one page (no hyphen). When multiple pages, or even one, you can use the pages property but each id with a hyphen prefix (`- id: xxxxxxx`).

Anyway, I've kept the `page` property for retro compatibility reasons. I didn't like the idea and your comment confirms my concerns: there should only be one way to declare settings (SSOT).

Therefore, use only the array method. I will update the documentation to avoid further misleading.
