### ISSUE TITLE
Inline databases

### ISSUE THREAD

**Issue by chrisboden** [emoriarty/jekyll-notion#87]
Enrique, thanks for the great work on this gem.

Is it possible to have a notion page with inline database (gallery view) converted to jekyll page with the gallery in tact? If not, how would you recommend tackling that. Use case is that there is a page which has a list of courses - the list of courses is in the form of an embedded database in gallery view. Thanks

**Comment by emoriarty** [comment]
Hello @chrisboden 👋 

I'm afraid not. According to markdown syntax there's not element that resembles the gallery view. Event with the extended syntax, the only thing that can (remotely) look like is a [table](https://www.markdownguide.org/extended-syntax/#tables) but the current matching element is a [simple table](https://www.notion.so/help/guides/simple-tables-vs-databases) block.

That said, what you can do is to use the database as [data object](https://github.com/emoriarty/jekyll-notion#data) in Jekyll. To do so, you must configure the database like this:
```yaml
notion:
  databases:
    - id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      data: gallery
```
A new dictionary object named gallery will be added to the site's data object and can be used in any template as follows:
```liquid
<ul class="carousel">
  {% for picture in site.data.gallery %}
    <li class="carousel-item"><img src="{{ picture.url }}" /></li>
  {% endfor %}
</ul>
```
You can now do some Javascript magic 😉

**Comment by chrisboden** [comment]
Thanks Enrique,

Understood on the inline databases. Thanks for the response.

I am working on an enhancement to your types.rb jekyll plugin for video embed handling that will save Notion page images and covers locally as I noticed that those images were pathed to S3 buckets on AWS and had expiring tokens attached to the urls - this rendered them invisible on my static pages after a short time. I will share gist as soon as I have it working well. Let me know if you had another solution for handling those expiring image urls. 

Secondly, a question about the way jekyll-notion saves files. I have a database id in the config.yml with a collection called 'articles' and at build/serve time, jekyll fetches the md pages for that database id and processes them with my 'notion' layout template which I set as default, per your tip. It then saves the processed output to the _site/articles dir as one would expect. 

However, I don't actually see those fetched md files anywhere in my root dir (ie pre-build), where all of my other md, html, etc page code lives - ie I only ever see the processed html files in the _site directory after build. Is there a setting I am missing somewhere that would allow those files to first saved to the root dir?

Thanks
Chris

**Comment by emoriarty** [comment]
Hello back,

Wow! Lots of questions. I'm answering one at a time:

> I am working on an enhancement to your types.rb jekyll plugin for video

I've already written an [article](https://enrq.me/dev/2023/03/31/embedding-videos-with-jekyll-notion/) tackling the video type.

> will save Notion page images and covers locally as I noticed that those images were pathed to S3 buckets on AWS and had expiring tokens attached to the urls - this rendered them invisible on my static pages after a short time. I will share gist as soon as I have it working well. Let me know if you had another solution for handling those expiring image urls.

I've did it some time ago and recently removed that code. Notion can eventually change the URL of the images or change the policies to fetch them. Not worth the effort. I recommend that you don't struggle too much and store the images in a CDN and then embed them in Notion. Images will be available from the CDN and not from Notion S3.

> Secondly, a question about the way jekyll-notion saves files. I have a database id in the config.yml with a collection called 'articles' and at build/serve time, jekyll fetches the md pages for that database id and processes them with my 'notion' layout template which I set as default, per your tip. It then saves the processed output to the _site/articles dir as one would expect.
However, I don't actually see those fetched md files anywhere in my root dir (ie pre-build), where all of my other md, html, etc page code lives - ie I only ever see the processed html files in the _site directory after build. Is there a setting I am missing somewhere that would allow those files to first saved to the root dir?

This is the purpose of jekyll-notion: using Notion has a CMS. No source file is present in the project but in Notion. Files are edited only in Notion. I have explained this in more detail [here](https://github.com/emoriarty/jekyll-notion/pull/68#issuecomment-1817475496).

**Comment by chrisboden** [comment]
Thanks Enrique,

I wanted to make sure that images and other file assets were available as static assets in my jekyll setup so that it remains a truly static site.

Made this little plugin which handles the local image aspect, fwiw.

Thanks again for your work on this.

https://gist.github.com/chrisboden/76e1097274dec768f763bba765e7079b
